apiVersion: v1
kind: Service
metadata:
  name: ilb-svc-my-app
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    run: my-app
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 8080